# Generated by Django 5.2 on 2025-04-13 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_user_is_email_verified_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_email_verified',
        ),
        migrations.DeleteModel(
            name='OTP',
        ),
    ]
