# Generated by Django 5.2 on 2025-05-05 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_review'),
    ]

    operations = [
    ]
